src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionCloudbeesFolderProperty/config.jelly
The previous code added the selected attribut to every option that did not fit the JobGroup.
~~Should I make a Jira Issue too?~~
https://issues.jenkins-ci.org/browse/JENKINS-28280
=> [JENKINS-28280] The selected-attribut was inverted

src/main/java/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionFolderProperty.java
```
May 12, 2015 3:58:03 PM hudson.ExtensionFinder$Sezpoz _find
WARNING: Failed to load jenkins.advancedqueue.jobinclusion.strategy.JobInclusionFolderProperty$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor
at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:625)
at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:614)
at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:345)
at hudson.ExtensionList.load(ExtensionList.java:300)
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:253)
at hudson.ExtensionList.iterator(ExtensionList.java:143)
at …
```
=> Avoid exceptions in log when optional plugin not installed

src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionJobProperty/config.jelly
I found another file where the select-attribute was inverted. I had forgot to look into all the `jelly.config` files.
This should be the last one.
I'm guessing I can link it to the same Jira-issue?
https://issues.jenkins-ci.org/browse/JENKINS-28280
Also, see #24 for the last Pull-Request.
=> The selected value was inverted

pom.xml, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/FolderPropertyLoader.java
https://issues.jenkins-ci.org/browse/JENKINS-37644
All the FolderPropertyXXXX has been changed to AbstractFolderXXXXX. Also Folder to AbstractFolder inside the method.
Please, @reviewbybees cc. @oleg-nenashev 
Based on @stephenc commit https://github.com/jenkinsci/unique-id-plugin/pull/11/files
=> [FIXED JENKINS-37644] - Update Folders Plugin dependency to fix the compatibility issue

src/main/java/jenkins/advancedqueue/sorter/strategy/FQBaseStrategy.java, src/test/java/jenkins/advancedqueue/sorter/strategy/FQStrategyTest.java, src/test/java/jenkins/advancedqueue/sorter/strategy/WFQStrategyTest.java
When a weight reached 1.00005 for instance, it was never increased
due to the comparison on floats.
Also, the weight was no more increased when the step became too small
compared to the minimum weight. As we are not using integers but
floats, the step must remain proportional to the weight.
=> [JENKINS-40284] - Fix blocked weights with FQ strategies

src/main/java/jenkins/advancedqueue/PrioritySorterConfiguration.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionJobProperty.java, src/main/java/jenkins/advancedqueue/priority/strategy/PriorityJobProperty.java
Generally this change is not binary compatible, and likely it requires 4.0. Not sure if the plugin can be really used in Pipeline without this fix. 
https://issues.jenkins-ci.org/browse/JENKINS-36570
CC @reviewbybees, @vitalii-vitrenko and @timothyclarke
=> [JENKINS-36570] - Cleanup references to AbstractProject in the core plugin classes

src/main/java/jenkins/advancedqueue/sorter/ItemInfo.java
If an ``ItemInfo`` object has the ``sortAsInQueueSince`` attribute set, the ``compareTo()`` method is not working correctly anymore.
The check, if we can sort by the InQueueSince time, is correctly using the ``getSortableInQueueSince()`` method, which includes the ``sortAsInQueueSince`` attribute and the ``inQueueSince`` attribute.
However, the actually comparison does not use this function and uses ``getInQueueSince()`` instead. Because of that the ``sortAsInQueueSince`` attribute is ignored and the objects are compared wrongly, leading to a wrongly sorted build queue.
Fix it using the ``getSortableInQueueSince()`` method not only in the check but also in the comparison.
=> [JENKINS-41419] Fix comparison of ItemInfo objects

.gitignore, src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java, src/main/java/jenkins/advancedqueue/priority/strategy/UpstreamCauseStrategy.java, src/main/java/jenkins/advancedqueue/sorter/AdvancedQueueSorter.java, src/main/java/jenkins/advancedqueue/sorter/StartedJobItemCache.java, src/test/java/jenkins/advancedqueue/test/UpstreamTest.java, src/test/java/jenkins/advancedqueue/testutil/JobHelper.java, src/test/resources/jenkins/advancedqueue/test/UpstreamTest/config.xml, src/test/resources/jenkins/advancedqueue/test/UpstreamTest/jenkins.advancedqueue.PriorityConfiguration.xml, src/test/resources/jenkins/advancedqueue/test/UpstreamTest/jenkins.advancedqueue.PrioritySorterConfiguration.xml
This change fixes the retrieval of the upstream job priority as well as a NPE in PriorityConfigurationPlaceholderTaskHelper occurring after a Jenkins restart in case there were pending jobs on shutdown.
=> [JENKINS-42584] upstream job priority ignored

src/main/java/jenkins/advancedqueue/JobGroup.java, src/main/java/jenkins/advancedqueue/PriorityConfiguration.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/FolderPropertyLoader.java, src/main/java/jenkins/advancedqueue/priority/strategy/BuildParameterStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/JobPropertyStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/UpstreamCauseStrategy.java, src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java, src/main/java/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy.java, src/test/java/jenkins/advancedqueue/test/UpstreamTest.java
There is a risk of NPEs in some cases, e.g. in "*Strategy#getPriority()" API. No related JIRA issues, but I would rather fix it.
=> Annotate methods which return explicit null

src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java
Mistake in #4 caught by https://github.com/jenkinsci/jenkins/pull/3120.
@reviewbybees esp. @oleg-nenashev
=> [JEP-200] Oops

src/main/java/jenkins/advancedqueue/PriorityConfiguration.java, src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java, src/main/java/jenkins/advancedqueue/PrioritySorterConfiguration.java, src/main/java/jenkins/advancedqueue/jobinclusion/JobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/FolderBasedJobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/PropertyBasedJobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/priority/PriorityStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/AbstractDynamicPriorityStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/AbstractStaticPriorityStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/BuildParameterStrategy.java, src/main/java/jenkins/advancedqueue/sorter/AdvancedQueueSorter.java, src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java
=> Cleanup getInstance() references and StringBuffer usages

src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java, src/main/resources/jenkins/advancedqueue/PriorityConfiguration/index.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/FolderBasedJobInclusionStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy/config.jelly
* Fix for view based priority sorting jelly
* [JENKINS-66938] Allow save of 2+ priority definitions
Special thanks to @monluk for the April 2021 fix to one of the issues discovered here.
See also:
* [JENKINS-67218](https://issues.jenkins.io/browse/JENKINS-67218) - Unable to store priority sorter configuration
* [JENKINS-65859](https://issues.jenkins.io/browse/JENKINS-65859) - "Priority Sorter Plugin" broken in 2.277.4 (though this fix does not resolve the issue described in that report)
=> [JENKINS-66938] Allow 2 or more priority definitions to be saved

src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy/config.jelly
**What was wrong**
In Jenkins - starting from version 2.264 - it was not possible to add or make changes to priority sorter for "Jobs included in a view".
Format of data in a json was not handled properly.
**What has been done**
Structure of elements in UI was wrong. The part of the UI responsible for filtering based on regular expression was placed inside views selector.
**How to test**
1. Install Jenkins version 2.264-2.277
2. Go to Job Priority and Add new priority sorter
3. Set "Jobs to include" to "Jobs included in a view"
4. Save changes
The test will result in "Oops!" page while using Priority Sorter plugin in version 4.0 and will work fine with the fixed version.
It has been tested and works fine on Jenkins 2.263.4 and 2.277.2
=> Fix for view based priority sorting jelly

pom.xml, src/main/java/jenkins/advancedqueue/ItemTransitionLogger.java, src/main/java/jenkins/advancedqueue/JobGroup.java, src/main/java/jenkins/advancedqueue/PriorityConfiguration.java, src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java, src/main/java/jenkins/advancedqueue/PrioritySorterConfiguration.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/FolderPropertyLoader.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/jobrestrictions/PrioritySorterRestriction.java, src/main/java/jenkins/advancedqueue/priority/strategy/BuildParameterStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/JobPropertyStrategy.java, src/main/java/jenkins/advancedqueue/priority/strategy/PriorityJobProperty.java, src/main/java/jenkins/advancedqueue/priority/strategy/UpstreamCauseStrategy.java, src/main/java/jenkins/advancedqueue/sorter/AdvancedQueueSorter.java, src/main/java/jenkins/advancedqueue/sorter/QueueItemCache.java, src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java, src/main/java/jenkins/advancedqueue/sorter/StartedJobItemCache.java, src/main/java/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy.java, src/test/java/jenkins/advancedqueue/test/UpstreamTest.java
* Remove uncalled private method
* Increase spotbugs effort to Max
* Set spotbugs threshold to 'Low'
* Remove unused imports
* Replace JSR-305 annotations with spotbugs
* Use lambda expressions to resolve spotbugs warning
* Remove unused imports
* Use lambda expressions to resolve spotbugs warning
* Suppress spotbugs warning from try with resources
* Suppress spotbugs warning for inner class
* Add Override annotations
* Suppress spotbugs warning for serialVersionID
* Return primary view if view is not correct type
* Use parameters for logger rather than concatenation
* Guard against NPE in constructor
* Use spotbugs annotations, not JSR-305
* Remove unused import
=> Add deeper spotbugs checks

pom.xml
GitHub is deprecating git:// protocol
=> Use https:// instead of git:// protocol

.github/dependabot.yml
Versions of GitHub Actions are another dependency to be maintained.
=> Check GitHub actions versions weekly

pom.xml
Also removes the version plugin configuration since the default configuration of the version plugin is sufficient for this plugin.
=> Enable pmd copy/paste detector report

README.md
Use the jenkins.io redirect that provides bug, improvement, and security issue reporting links.
=> Add 'Report an issue' link to documentation

pom.xml
https://stats.jenkins.io/pluginversions/PrioritySorter.html shows that 88% of installations of priority sorter plugin 4.0.0 are on Jenkins 2.277.1 or later.  Users that are likely to adopt newer versions of the plugin are also likely to adopt newer versions of Jenkins.
The preceding version, 3.6.0, has only 8% of its installations on 2.277.1 or newer.  Since 3.6.0 has a tables to divs issue, it is not surprising that users are not updating to the newest Jenkins version until they update to the newest version of the plugin.
=> Require Jenkins 2.277.1 or later

src/main/resources/jenkins/advancedqueue/PriorityConfiguration/index.jelly
Do not need the conditional for div based layout.  The plugin only supports versions that provide div based layout.
=> Remove divBasedFormLayout jelly conditionals

Jenkinsfile
JDK 8 support will eventually be dropped from Jenkins.  Test both JDK 8 and JDK 11 until this plugin requires Java 11 or newer.
=> Test JDK 8 and JDK 11 in ci

Jenkinsfile, pom.xml, src/main/java/jenkins/advancedqueue/RunExclusiveThrottler.java
60% of installations of the most recent release of the plugin (now 9 months old) are running Jenkins 2.346.1 or newer based on the [install stats](https://stats.jenkins.io/pluginversions/PrioritySorter.html). Jenkins 2.346.3 is a good choice as the last LTS version before Jenkins core requires Java 11.
- Remove unused exclusion
- Require Jenkins 2.346.3 or newer
- Test with nested view plugin 1.26
Resolves a GitHub false positive warning about the nested view plugin 1.24 vulnerability.  Since the nested-view plugin dependency is only in test scope, vulnerabilities in that plugin do not affect this plugin.
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> Require Jenkins 2.346.3 or newer

pom.xml, src/test/java/jenkins/advancedqueue/test/MatrixTest.java, src/test/java/jenkins/advancedqueue/test/PrioritySorterConfigurationTest.java
[JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
This pull request introduces new tests for the PrioritySorterConfiguration class, specifically targeting the doFillStrategyItems method.
The doFillStrategyItems method is responsible for populating a ListBoxModel with the display names and keys of all sorter strategies. The test, testDoFillStrategyItems, ensures that this List BoxModel is correctly populated.
The test leverages Mockito to mock the SorterStrategyDescriptor instances and their respective methods, getDisplayName and getKey. It verifies that the ListBoxModel returned by doFillStrategyItems contains the correct number of items and that each item's name and value match the expected values.
=> JENKINS-69757 Improve priority sorter plugin automated test coverage

src/test/java/jenkins/advancedqueue/test/MatrixTest.java
Practicing what I regularly preach.  I don't have time or energy to determine why the test is flaky.  There are several other tests in the same file.  Delete the flaky test rather than continuing to be distracted by it.
Before this change, 2 of 10 test runs failed on my computer.  After this change, 16 of 16 tests runs passed.
=> Remove flaky test

pom.xml, src/main/java/jenkins/advancedqueue/PrioritySorterConfiguration.java
Suppress an unread field warning to retain compatibility.
Initialize strategy to avoid spotbugs warning
No evidence of any detected bug, but initializing a field in the constructor seems reasonable, especially since it is using the value that is assigned in the init() method.
Automated tests pass and the code is covered by the automated tests.
=> Use spotbugs 4.8.2

src/test/java/org/kohsuke/stapler/MockStaplerRequest.java
The javax.annotation.Nonnull has been deprecated for a long time and is steadily being removed from Jenkins.
=> Replace deprecated javax annotation with spotbugs annotation

src/spotbugs/excludesFilter.xml
Floating point equality test in this case is reasonable since it is being used in a compareTo method.
Confirmed the suppressed warning is no longer reported.
```[tasklist]
```
=> Suppress future spotbugs warning for equals test

src/main/resources/jenkins/advancedqueue/jobrestrictions/PrioritySorterRestriction/config.jelly, src/main/resources/jenkins/advancedqueue/jobrestrictions/PrioritySorterRestriction/update-list-box.js, src/main/resources/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy/update-list-box.js
https://issues.jenkins.io/browse/JENKINS-73910
The functionality of updating the values in the dropdown was broken. Seems like the signature of `updateListBox` has changed since the time this code was written. So I've fixed that along with the extraction.
https://www.loom.com/share/414196ed73624dff9770c2882c1ed3a0
https://www.loom.com/share/d42712cdecde4c77a09fb273a5ab4102
https://www.loom.com/share/13c333dfd5054605b1c7cbb46a650a60
https://www.loom.com/share/a118cc996c4a4552a233cf29774430e1
=> [JENKINS-73910] Extract inline event handlers to separate JavaScript files

src/test/java/jenkins/advancedqueue/jobrestrictions/PrioritySorterRestrictionTest.java
This pull request introduces unit tests for the `PrioritySorterRestriction` class to address the issue outlined in [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757). 
These tests ensure the class functions correctly and handles various scenarios, such as missing `ItemInfo` and priority range validations.
These tests increase the code coverage of the code-base.
- Automated tests were implemented to ensure complete coverage of the `PrioritySorterRestriction` logic:
- `testCanTake_MissingItemInfo`: Verifies behavior when `ItemInfo` is absent in the `QueueItemCache`.
- `testCanTake_PriorityRange`: Tests `canTake` behavior for different priority values, validating edge conditions.
- `testGetterMethods`: Ensures the correctness of getter methods and that `canTake` works with `Run` …
=> Add unit tests for PrioritySorterRestriction class to address JENKINS-69757

src/test/java/jenkins/advancedqueue/util/PrioritySorterUtilTest.java
To improve test coverage for the plugin as described [here](https://issues.jenkins.io/browse/JENKINS-69757), this PR adds tests to a class used to fill a ListBoxModel with the specified priorities. The tests asserts that lists are properly created according to the parameters passed.
=> Address JENKINS-69757 by adding tests for util class

src/test/java/jenkins/advancedqueue/priority/strategy/HealthStrategyTest.java
This Pull Request aims to improve test coverage for the plugin (as described [here](https://issues.jenkins.io/browse/JENKINS-69757)) by creating tests for the priority package.
The test coverage for HealthStrategy class was:
When this PR closes, the coverage will be:
=> [JENKINS-69757] - Improving test coverage for health strategy

src/test/java/jenkins/advancedqueue/jobinclusion/strategy/FolderBasedJobInclusionStrategyTest.java, src/test/java/jenkins/advancedqueue/util/PrioritySorterUtilTest.java
Add test for FolderBasedJobInclusionStrategy class
Fixes [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
=> Add test for FolderBasedJobInclusionStrategy class

src/test/java/jenkins/advancedqueue/testutil/TestRunListener.java
New tests do not need to initialize the test run listener
Confirmed that existing tests pass and new tests no longer report a null pointer exception to the log.
=> Do not require TestRunListener.init() before use

pom.xml
The [stackoverflow article](https://stackoverflow.com/questions/12038238/unable-to-locate-source-xref-to-link-to) describes the rationale.  We don't need linked source code reports, so it is safe to globally disable `linkXRef`.
Confirmed that `mvn verify` before this change outputs 3 messages warning about XREF and that after this change those messages are not shown.
=> Silence XREF warning in Maven output

src/main/java/jenkins/advancedqueue/JobGroup.java, src/main/java/jenkins/advancedqueue/jobinclusion/JobInclusionStrategy.java, src/main/java/jenkins/advancedqueue/jobinclusion/strategy/PropertyBasedJobInclusionStrategy.java, src/test/java/jenkins/advancedqueue/jobinclusion/strategy/PropertyBasedJobInclusionStrategyTest.java
Add test for PropertyBasedJobInclusionStrategy class
Fixes JIRA issue [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
=> Add test for PropertyBasedJobInclusionStrategy class

src/main/java/jenkins/advancedqueue/priority/strategy/JobPropertyStrategy.java, src/test/java/jenkins/advancedqueue/priority/strategy/JobPropertyStrategyTest.java
Part of [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
Added tests for the `JobPropertyStrategy` class. The tests added cover the case when the `WhengetPriorityInternal` function returns null.
Test coverage before:
Test coverage after:
=> Added tests for JobPropertyStrategy class

src/test/java/jenkins/advancedqueue/sorter/SorterStrategyDescriptorTest.java
Add test for SorterStrategyDescriptor class
Aims to Fix [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
=> Add test for SorterStrategyDescriptor class

src/main/java/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy.java, src/test/java/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategyTest.java
Add test for MultiBucketStrategy class and Made getStrategy method package-protected and condition for non-integer input.
=> Add test for MultiBucketStrategy class

src/test/java/jenkins/advancedqueue/priority/strategy/PriorityJobPropertyTest.java
Restore a loss that I caused in the original test created by @yashpal2104.  Thanks very much to @yashpal2104 for detecting the loss!
@yashpal2104 I'd love to have your review to be sure that I corrected my earlier mistakes.
Expand tests for existing and non-existing views.
Amends https://github.com/jenkinsci/priority-sorter-plugin/pull/437 to correct mistakes that I made while reviewing that pull request.
Confirmed that test pass on my Linux computer.
=> Use existing view in the job group test

pom.xml, src/test/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelperTest.java
=> Add test for PriorityConfigurationPlaceholderTaskHelper class

src/main/resources/jenkins/advancedqueue/PriorityConfiguration/index.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/FolderBasedJobInclusionStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionCloudbeesFolderProperty/config.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionJobProperty/config.jelly, src/main/resources/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/priority/strategy/AbstractStaticPriorityStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/priority/strategy/HealthStrategy/config.jelly, src/main/resources/jenkins/advancedqueue/priority/strategy/PriorityJobProperty/config.jelly
all selects now use the correct styling
Before:
After:
=> apply proper styling to selects

pom.xml
Declare the plugin bundles no dependencies.
Ban JUnit 4 imports since the plugin's tests are in JUnit 5.
Confirmed that plugin compiles.
=> Declare dependencies and ban JUnit 4 imports
