jenkinsci/priority-sorter-plugin

pom.xml
src/main/java/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy.java
src/test/java/jenkins/advancedqueue/test/NestedViewTest.java
src/test/resources/jenkins/advancedqueue/test/NestedViewTest/config.xml
src/test/resources/jenkins/advancedqueue/test/NestedViewTest/jenkins.advancedqueue.PriorityConfiguration.xml
src/test/resources/jenkins/advancedqueue/test/NestedViewTest/jenkins.advancedqueue.PrioritySorterConfiguration.xml

This also fixes [JENKINS-24962] as NestedView is based on ViewGroup

Added support for ViewGroup in ViewBasedJobInclusion.

---

src/main/java/jenkins/advancedqueue/jobinclusion/strategy/ViewBasedJobInclusionStrategy.java

Just saw that in the logs, better with the right wording :)

Fix exixts -> exist typo

---

pom.xml
src/main/java/jenkins/advancedqueue/PriorityConfiguration.java
src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java

[[JENKINS-36570]](https://issues.jenkins-ci.org/browse/JENKINS-36570)

[JENKINS-36570] Implement pipeline compatibility

---

src/main/java/jenkins/advancedqueue/ItemTransitionLogger.java
src/main/java/jenkins/advancedqueue/PriorityConfigurationPlaceholderTaskHelper.java
src/main/java/jenkins/advancedqueue/sorter/AdvancedQueueSorter.java
src/main/java/jenkins/advancedqueue/sorter/QueueItemCache.java
src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java

This PR fixes two issues reported in [JENKINS-44014](https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-44014). I assume both issues are related to the newly introduced Pipeline support, hence @reviewbybees 
* Prevent class cast exception and add diagnostics if the `ownerTask` of Pipeline placeholder is not a Job. Multibranch?
* Prevent NullPointerException in `AdvancedQueueSorter#onLeft()` when item is missing in the queue
CC @jglick who commented to this pull request

[JENKINS-44014] - Fix the reported runtime exceptions (Pipeline integration)

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/release-drafter.yml
CHANGELOG.md
README.md

@oleg-nenashev Enable Release Drafter and Dependabot

---

README.md
docs/CHANGELOG.old.md

Move changelog to GitHub releases

---

README.md

- Assorted typos and grammar fixes
- Couple of minor text improvements
- Several Markdown formatting fixes/(consistency) improvements

Spelling fixes and formatting improvements

---

pom.xml

Document that Mark Waite is now maintaining this plugin.

Add Mark Waite as a maintainer

---

src/main/java/jenkins/advancedqueue/sorter/SorterStrategyDescriptor.java
src/main/java/jenkins/advancedqueue/sorter/strategy/MultiBucketStrategy.java

Extracted from https://github.com/jenkinsci/priority-sorter-plugin/pull/43

Update author info on two files

---

.github/labeler.yml
.github/workflows/labeler.yml

Some files have a standard theme for a label, like the `chore` label for the contents of the `.github` and `.mvn` directories.

Automate pull request labeling

---

Jenkinsfile

Find more problems is better than fast failure

Let all tests complete

---

pom.xml

Script security release completed

Remove script security exclusion

---

.github/release-drafter.yml

Plugin is using 3 component versioning

Use patch format x.yy.zz for release drafter

---

Jenkinsfile

Rare to have a failure that benefits from fail fast

Run all CI configurations to completion

---

src/test/resources/jenkins/advancedqueue/test/BasicTest/config.xml
src/test/resources/jenkins/advancedqueue/test/JobPatternGroupTest/config.xml
src/test/resources/jenkins/advancedqueue/test/MultipleMatchJobGroupTest/config.xml
src/test/resources/jenkins/advancedqueue/test/NestedViewTest/config.xml
src/test/resources/jenkins/advancedqueue/test/OneJobGroupTest/config.xml
src/test/resources/jenkins/advancedqueue/test/SectionedViewTest/config.xml
src/test/resources/jenkins/advancedqueue/test/UpstreamTest/config.xml

Replaced deprecated `CaseInsensitiveComparator` with `java.lang.String` one in tests

---

pom.xml

https://github.com/jenkinsci/bom/releases/tag/2179.v0884e842b_859

Use plugin BOM 2179.v0884e842b_859

---

Jenkinsfile
pom.xml
src/test/java/jenkins/advancedqueue/test/MatrixTest.java

- Run tests with multiple cores in CI
- Use simpler scm tag in pom.xml
Automated tests pass in Java 17 on Linux.

Run tests with multiple cores in CI

---

src/test/java/jenkins/advancedqueue/jobinclusion/strategy/FolderPropertyLoaderTest.java

Added a new test class for FolderPropertyLoader class

Add test for FolderPropertyLoader class

---

src/test/java/jenkins/advancedqueue/jobinclusion/JobInclusionJobPropertyTest.java
src/test/java/jenkins/advancedqueue/jobinclusion/strategy/JobInclusionJobPropertyTest.java

Part of [JENKINS-69757](https://issues.jenkins.io/browse/JENKINS-69757)
Added tests for the `JobInclusionJobProperty` class.
Test coverage before:
Test coverage after:

Added tests for JobInclusionJobProperty class

---

src/test/java/jenkins/advancedqueue/priority/strategy/BuildParameterStrategyTest.java

Add test for BuildParameterStrategy class

Add test for BuildParameterStrategy class

---

src/main/java/jenkins/advancedqueue/priority/strategy/PriorityJobProperty.java
src/test/java/jenkins/advancedqueue/priority/strategy/PriorityJobPropertyTest.java

Add tests for PriorityJobProperty class and introduced a new conditional to check if form is empty or null

Add tests for PriorityJobProperty class

---

src/main/java/jenkins/advancedqueue/sorter/SorterStrategy.java
src/test/java/jenkins/advancedqueue/sorter/SorterStrategyTest.java

Add test for Sorter strategy 
